version: "3"
services:
  hotel-app:
    container_name: hotel-app
    restart: always
    build: .
    ports:
      - "9090:9090"
    volumes:
      - hotel-app-data:/usr/src/app
    networks:
      - tuto-network

volumes:
  hotel-app-data:
    driver_opts:
      type: none
      device: /home/tiloic/dev/formations/node/hotel-app-console/src
      o: bind
  dbdata:

networks:
  tuto-network:
    driver: bridge
